#!/usr/bin/env ruby
#The SwiftScript language!
#
#usage:
# ./swift_script example #to eval a file
# ./swift_script #to start the REPL
#

$:.unshift "." #Fix for Ruby 1.9
require 'swift_script'
require 'readline'

interpreter = SwiftScript::Interpreter.new

if file = ARGV.first
  interpreter.eval File.read(file)
else
  puts "SwiftScript REPL, CTRL+C to quit"
  loop do
    line = Readline::readline(">>")
    Readline::HISTORY.push(line)
    value = interpreter.eval(line)
    puts "=> #{value.ruby_value.inspect}"
  end
end
